"""Modify subreddit in RedditPainPoint to subreddits

Revision ID: 3523bb7e9b4e
Revises: 49be3fd6f5a9
Create Date: 2026-08-02 10:27:45.803736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3523bb7e9b4e'
down_revision: Union[str, Sequence[str], None] = '49be3fd6f5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subreddits', sa.Text(), nullable=False),
    sa.Column('scrape_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('pain_point_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_jobs_id'), 'reddit_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_jobs_status'), 'reddit_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_reddit_jobs_user_id'), 'reddit_jobs', ['user_id'], unique=False)
    op.create_table('reddit_pain_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('subreddits', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['reddit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_pain_points_job_id'), 'reddit_pain_points', ['job_id'], unique=False)
    op.create_index(op.f('ix_reddit_pain_points_subreddits'), 'reddit_pain_points', ['subreddits'], unique=False)
    op.create_table('reddit_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['reddit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'post_id', name='uq_reddit_posts_job_post')
    )
    op.create_index(op.f('ix_reddit_posts_job_id'), 'reddit_posts', ['job_id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_post_id'), 'reddit_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_subreddit'), 'reddit_posts', ['subreddit'], unique=False)
    op.create_table('reddit_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['reddit_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'comment_id', name='uq_reddit_comments_post_comment')
    )
    op.create_index(op.f('ix_reddit_comments_comment_id'), 'reddit_comments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_reddit_comments_post_id'), 'reddit_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_reddit_comments_subreddit'), 'reddit_comments', ['subreddit'], unique=False)
    op.create_table('reddit_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pain_point_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pain_point_id'], ['reddit_pain_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_evidence_pain_point_id'), 'reddit_evidence', ['pain_point_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_evidence_pain_point_id'), table_name='reddit_evidence')
    op.drop_table('reddit_evidence')
    op.drop_index(op.f('ix_reddit_comments_subreddit'), table_name='reddit_comments')
    op.drop_index(op.f('ix_reddit_comments_post_id'), table_name='reddit_comments')
    op.drop_index(op.f('ix_reddit_comments_comment_id'), table_name='reddit_comments')
    op.drop_table('reddit_comments')
    op.drop_index(op.f('ix_reddit_posts_subreddit'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_post_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_job_id'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    op.drop_index(op.f('ix_reddit_pain_points_subreddits'), table_name='reddit_pain_points')
    op.drop_index(op.f('ix_reddit_pain_points_job_id'), table_name='reddit_pain_points')
    op.drop_table('reddit_pain_points')
    op.drop_index(op.f('ix_reddit_jobs_user_id'), table_name='reddit_jobs')
    op.drop_index(op.f('ix_reddit_jobs_status'), table_name='reddit_jobs')
    op.drop_index(op.f('ix_reddit_jobs_id'), table_name='reddit_jobs')
    op.drop_table('reddit_jobs')
    # ### end Alembic commands ###
