"""Add username field

Revision ID: 47d8d6c1d31a
Revises: a57a93877261
Create Date: 2026-01-26 11:52:24.932636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47d8d6c1d31a"
down_revision: Union[str, Sequence[str], None] = "a57a93877261"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_verifications",
        "is_used",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )

    # 1. Add column as nullable first
    op.add_column(
        "users", sa.Column("username", sa.String(length=30), nullable=True)
    )

    # 2. Populate existing rows with a unique username (e.g., 'user_' + start of UUID)
    op.execute("UPDATE users SET username = 'user_' || substr(id, 1, 8)")

    # 3. Alter to non-nullable
    op.alter_column("users", "username", nullable=False)

    # 4. Create unique index
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    op.alter_column(
        "email_verifications",
        "is_used",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
