"""Add stripe_subscription_id to User

Revision ID: 49be3fd6f5a9
Revises: 2633c9c4d17e
Create Date: 2026-08-02 07:11:43.300735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49be3fd6f5a9"
down_revision: Union[str, Sequence[str], None] = "2633c9c4d17e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column(
            "stripe_subscription_id", sa.String(length=255), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "stripe_subscription_id")
