"""Add new_page column to RedditJob

Revision ID: 4db1f946816f
Revises: 96ed3a57e025
Create Date: 2026-08-10 15:55:32.983260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db1f946816f'
down_revision: Union[str, Sequence[str], None] = '96ed3a57e025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_jobs', sa.Column('new_page', sa.Boolean(), nullable=False))
    op.alter_column('reddit_jobs', 'analysis_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reddit_jobs', 'analysis_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'template'::character varying"),
               existing_nullable=False)
    op.drop_column('reddit_jobs', 'new_page')
    # ### end Alembic commands ###
