"""Remove new_page column, and add sorting_type to RedditJob

Revision ID: 5e2ce05e84ce
Revises: 4db1f946816f
Create Date: 2026-08-10 16:12:37.086155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2ce05e84ce'
down_revision: Union[str, Sequence[str], None] = '4db1f946816f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_jobs', sa.Column('sorting_type', sa.String(length=20), nullable=False))
    op.drop_column('reddit_jobs', 'new_page')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_jobs', sa.Column('new_page', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('reddit_jobs', 'sorting_type')
    # ### end Alembic commands ###
