"""Change back to subreddit str

Revision ID: 635f4374a22a
Revises: 769d36fbc448
Create Date: 2026-08-03 12:25:22.007299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635f4374a22a'
down_revision: Union[str, Sequence[str], None] = '769d36fbc448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_pain_points', sa.Column('subreddit', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_reddit_pain_points_subreddits'), table_name='reddit_pain_points')
    op.create_index(op.f('ix_reddit_pain_points_subreddit'), 'reddit_pain_points', ['subreddit'], unique=False)
    op.drop_column('reddit_pain_points', 'subreddits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_pain_points', sa.Column('subreddits', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reddit_pain_points_subreddit'), table_name='reddit_pain_points')
    op.create_index(op.f('ix_reddit_pain_points_subreddits'), 'reddit_pain_points', ['subreddits'], unique=False)
    op.drop_column('reddit_pain_points', 'subreddit')
    # ### end Alembic commands ###
