"""Add target_audience field

Revision ID: 769d36fbc448
Revises: a8f3b2c1d9e0
Create Date: 2026-08-03 09:38:48.560023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "769d36fbc448"
down_revision: Union[str, Sequence[str], None] = "a8f3b2c1d9e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reddit_pain_points",
        sa.Column("target_audience", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reddit_pain_points", "target_audience")
    # ### end Alembic commands ###
