"""Change content from RedditEvidence into quote

Revision ID: a4e505c83b3d
Revises: 41208b6acd9c
Create Date: 2026-08-05 18:29:58.721183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e505c83b3d'
down_revision: Union[str, Sequence[str], None] = '41208b6acd9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_evidence', sa.Column('quote', sa.Text(), nullable=False))
    op.drop_column('reddit_evidence', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_evidence', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('reddit_evidence', 'quote')
    # ### end Alembic commands ###
