"""rename_created_utc_to_created_at

Revision ID: eaf27cc0050f
Revises: f6fdfe9ceb9c
Create Date: 2026-07-31 10:58:00.455354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaf27cc0050f'
down_revision: Union[str, Sequence[str], None] = 'f6fdfe9ceb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE reddit_comments RENAME COLUMN created_utc TO created_at')
    op.execute('ALTER TABLE reddit_comments ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING to_timestamp(created_at)')
    op.execute('ALTER TABLE reddit_posts RENAME COLUMN created_utc TO created_at')
    op.execute('ALTER TABLE reddit_posts ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING to_timestamp(created_at)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE reddit_posts RENAME COLUMN created_at TO created_utc')
    op.execute('ALTER TABLE reddit_posts ALTER COLUMN created_utc TYPE DOUBLE PRECISION USING extract(epoch from created_utc)')
    op.execute('ALTER TABLE reddit_comments RENAME COLUMN created_at TO created_utc')
    op.execute('ALTER TABLE reddit_comments ALTER COLUMN created_utc TYPE DOUBLE PRECISION USING extract(epoch from created_utc)')
    # ### end Alembic commands ###
